<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uam_rpc.proto

namespace Inexdigital\UamAuthorization\Grpc\Uam\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>app.EnforcerConfigResponse</code>
 */
class EnforcerConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string model = 1;</code>
     */
    protected $model = '';
    /**
     * Generated from protobuf field <code>repeated .app.PolicyList policy_list = 2;</code>
     */
    private $policy_list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $model
     *     @type \Inexdigital\UamAuthorization\Grpc\Uam\Api\PolicyList[] $policy_list
     * }
     */
    public function __construct($data = NULL) {
        \Inexdigital\UamAuthorization\Grpc\Uam\GPBMetadata\UamRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string model = 1;</code>
     * @return string
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Generated from protobuf field <code>string model = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .app.PolicyList policy_list = 2;</code>
     * @return RepeatedField<\Inexdigital\UamAuthorization\Grpc\Uam\Api\PolicyList>
     */
    public function getPolicyList()
    {
        return $this->policy_list;
    }

    /**
     * Generated from protobuf field <code>repeated .app.PolicyList policy_list = 2;</code>
     * @param \Inexdigital\UamAuthorization\Grpc\Uam\Api\PolicyList[] $var
     * @return $this
     */
    public function setPolicyList(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inexdigital\UamAuthorization\Grpc\Uam\Api\PolicyList::class);
        $this->policy_list = $arr;

        return $this;
    }

}

