<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uam_rpc.proto

namespace Inexdigital\Enforcer\Grpc\Uam\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>app.EnforceResponse</code>
 */
class EnforceResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Inexdigital\Enforcer\Grpc\Uam\GPBMetadata\UamRpc::initOnce();
        parent::__construct($data);
    }

}

