<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uam_rpc.proto

namespace Inexdigital\UamAuthorization\Grpc\Uam\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>app.EnforcerConfigRequest</code>
 */
class EnforcerConfigRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Inexdigital\UamAuthorization\Grpc\Uam\GPBMetadata\UamRpc::initOnce();
        parent::__construct($data);
    }

}

