<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uam_rpc.proto

namespace Inexdigital\Enforcer\Grpc\Uam\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>app.PolicyList</code>
 */
class PolicyList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string policy = 1;</code>
     */
    private $policy;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $policy
     * }
     */
    public function __construct($data = NULL) {
        \Inexdigital\Enforcer\Grpc\Uam\GPBMetadata\UamRpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string policy = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPolicy()
    {
        return $this->policy;
    }

    /**
     * Generated from protobuf field <code>repeated string policy = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPolicy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->policy = $arr;

        return $this;
    }

}

